"""
This is a setup.py script generated by py2app

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = [{'script': 'start_gemini.py', 'name': 'Gemini CLI Launcher'}]
APP_NAME = "Gemini CLI Launcher"
DATA_FILES = ['run_gemini_logic.sh']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'app.icns', # 您需要提供一個圖示檔案，如果沒有，可以先移除這行
    'packages': ['tkinter'],
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Launches the Gemini CLI with custom settings",
        'CFBundleIdentifier': "com.lalahuang.gemini-cli-launcher",
        'CFBundleVersion': "1.0.0",
        'CFBundleShortVersionString': "1.0",
        'NSHumanReadableCopyright': u"Copyright © 2025, lala.huang, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# It is recommended to run py2app with the following command now:
# python3 setup.py py2app --semi-standalone
